#!/usr/bin/bash
gcc Test.c -lm -g -o test ../src/arb.c ../src/command.c ../src/compute.c ../src/functions.c ../src/general.c ../src/highlight.c ../src/misc.c ../src/parser.c ../src/print.c ../src/units.c
./test $1 $2 $3 $4